version: '3.7'

services:
  backend:
    image: "node:14"
    volumes:
      - "./:/app"
    expose:
      - "3000"
    command: bash -c "npm i && npm run dev"
    working_dir: /app
    ports:
      - 3000:3000
    links:
      - redis
    depends_on:
      - redis
    networks:
      - local

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/data
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  redis:
